// Daily morning briefing — texts every opted-in user a 3-line summary.
//
// Wired in vercel.json at "0 13 * * *" (8am Eastern). The briefing is
// generated by the same agent the user texts with — same memory, same
// citations, same workspace scoping — but with a fixed objective.
//
// Auth: CRON_SECRET (Vercel cron). Also accepts ?user=<uuid> with the
// same secret to fire on-demand for /digest commands.

import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { runSmsAgent } from "@/lib/sms/agent";
import { sendMessage } from "@/lib/sms/sender";
import { isWithinQuietHours } from "@/lib/sms/commands";
import { getIndustryConfig } from "@/lib/industry/config";

export const dynamic = "force-dynamic";
export const maxDuration = 300;

const BRIEFING_OBJECTIVE = `Generate this user's morning briefing as if you were texting them. 3 lines max. Format:

Line 1: today's most time-sensitive item (a meeting, a deadline, a flag from /planning or /compliance) — be specific.
Line 2: one client / property worth a proactive touch today (stale, expiring doc, recent signal).
Line 3: one thing the user explicitly asked you to remind them of, or "Nothing else flagged."

Use memory.search and clients.query to ground each line. No greeting, no sign-off. Just the three lines.`;

async function handle(request: NextRequest) {
  const url = new URL(request.url);
  const auth = request.headers.get("authorization") || "";
  const bearer = auth.replace(/^Bearer\s+/i, "");
  const secret = process.env.CRON_SECRET;
  if (secret && bearer !== secret && url.searchParams.get("key") !== secret) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const targetUser = url.searchParams.get("user");

  // Pull eligible users
  let query = supabaseAdmin
    .from("profiles")
    .select(
      "id, workspace_id, full_name, sms_phone, sms_verified_at, sms_briefing_enabled, sms_quiet_start, sms_quiet_end, sms_timezone",
    )
    .not("sms_phone", "is", null)
    .not("sms_verified_at", "is", null);
  if (targetUser) {
    query = query.eq("id", targetUser);
  } else {
    query = query.eq("sms_briefing_enabled", true);
  }

  const { data: users, error } = await query;
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  const results: Array<{ user: string; ok: boolean; error?: string }> = [];

  for (const u of users || []) {
    const profile = u as any;
    if (!profile.workspace_id) continue;
    if (
      !targetUser &&
      isWithinQuietHours(profile.sms_quiet_start, profile.sms_quiet_end)
    ) {
      results.push({ user: profile.id, ok: false, error: "quiet hours" });
      continue;
    }
    try {
      const { data: ws } = await supabaseAdmin
        .from("workspaces")
        .select("name, industry")
        .eq("id", profile.workspace_id)
        .maybeSingle();
      const industry = (ws as any)?.industry as string | null;
      const config = getIndustryConfig(industry);
      const result = await runSmsAgent({
        workspaceId: profile.workspace_id,
        userId: profile.id,
        phone: profile.sms_phone,
        body: BRIEFING_OBJECTIVE,
        industry,
        assistantName: config.assistantName || "Dante",
        userName: profile.full_name || null,
        workspaceName: (ws as any)?.name || null,
        userTimezone: profile.sms_timezone || "America/New_York",
      });
      await sendMessage(profile.sms_phone, result.reply, {
        workspaceId: profile.workspace_id,
        userId: profile.id,
        source: "sms_briefing",
      });
      results.push({ user: profile.id, ok: true });
    } catch (err: any) {
      console.error(`[sms.briefing] user ${profile.id} failed:`, err?.message);
      results.push({ user: profile.id, ok: false, error: err?.message });
    }
  }

  return NextResponse.json({ ok: true, count: results.length, results });
}

export async function GET(req: NextRequest) {
  return handle(req);
}
export async function POST(req: NextRequest) {
  return handle(req);
}
