// app/api/dante/n8n/execution-callback/route.ts
//
// Push callback endpoint for n8n workflow executions. Every n8n workflow
// generated by Dante includes a mandatory final "Report to Drift" node
// (an HTTP Request node) that POSTs execution results here. An n8n Error
// Trigger workflow also POSTs here on any execution failure.
//
// This is the PRIMARY mechanism for execution status updates (per
// advisory board requirement). Polling the n8n execution API is the
// fallback only.
//
// Auth: DRIFT_N8N_CALLBACK_SECRET header. The same secret is embedded
// in the "Report to Drift" node's headers when the workflow is generated.

import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { log as rootLog } from "@/lib/logging";
import type { N8nExecutionCallback } from "@/lib/dante/n8n-types";

const callbackLog = rootLog.child({ component: "n8n-callback" });

export const dynamic = "force-dynamic";

export async function POST(request: Request) {
  // Verify callback secret
  const secret = request.headers.get("x-drift-n8n-secret");
  const expected = process.env.DRIFT_N8N_CALLBACK_SECRET;
  if (!expected || secret !== expected) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let payload: N8nExecutionCallback;
  try {
    payload = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const {
    n8n_execution_id,
    n8n_workflow_id,
    status,
    started_at,
    finished_at,
    result_summary,
    error_message,
  } = payload;

  if (!n8n_execution_id || !n8n_workflow_id || !status) {
    return NextResponse.json(
      { error: "Missing required fields: n8n_execution_id, n8n_workflow_id, status" },
      { status: 400 },
    );
  }

  callbackLog.info(
    "received execution callback",
    { n8n_execution_id, n8n_workflow_id, status },
  );

  // Look up the Drift workflow by its n8n_workflow_id
  const { data: driftWorkflow } = await supabaseAdmin
    .from("dante_workflows")
    .select("id, workspace_id, name")
    .eq("n8n_workflow_id", n8n_workflow_id)
    .maybeSingle();

  if (!driftWorkflow) {
    // Workflow might have been deleted from Drift but still running in n8n.
    // Log and accept -- do not error so n8n does not retry.
    callbackLog.warn(
      "callback for unknown Drift workflow (may have been deleted)",
      { n8n_workflow_id },
    );
    return NextResponse.json({ ok: true, matched: false });
  }

  // Close out the run row. The run route inserts a `running` row when it
  // fires the webhook, but n8n's onReceived webhook response carries no
  // execution id — that row's n8n_execution_id is "unknown". So matching
  // by n8n_execution_id alone can never find it (and the old upsert on a
  // non-unique column failed outright, leaving runs stuck on "running"
  // forever). Match the open running row for this workflow instead, and
  // only insert a fresh row when there isn't one (cron/webhook-triggered
  // executions that never went through the run route).
  // NB: dante_workflow_runs has a CHECK constraint allowing only
  // queued/running/success/error/cancelled/waiting_approval — writing
  // "completed"/"failed" (the old behavior) violates it and the write
  // silently dies, leaving the run stuck on "running".
  const terminalStatus = status === "success" ? "success" : "error";
  // The runs table stores execution output in `output` (there is no
  // `result` column — writing one made PostgREST reject the whole row).
  const resultPayload = {
    n8n_execution_id,
    status,
    output: result_summary || null,
    error: error_message || null,
  };

  const { data: openRun } = await supabaseAdmin
    .from("dante_workflow_runs")
    .select("id")
    .eq("workflow_id", driftWorkflow.id)
    .eq("status", "running")
    .order("started_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (openRun) {
    const { error: updateErr } = await supabaseAdmin
      .from("dante_workflow_runs")
      .update({
        status: terminalStatus,
        finished_at: finished_at || new Date().toISOString(),
        output: resultPayload,
        n8n_execution_id,
        error: error_message || null,
      })
      .eq("id", openRun.id);
    if (updateErr) {
      callbackLog.error(
        "failed to close open run",
        { err: updateErr.message, run_id: openRun.id, n8n_execution_id },
      );
    }
  } else {
    const { error: insertErr } = await supabaseAdmin
      .from("dante_workflow_runs")
      .insert({
        workflow_id: driftWorkflow.id,
        workspace_id: driftWorkflow.workspace_id,
        status: terminalStatus,
        started_at: started_at || new Date().toISOString(),
        finished_at: finished_at || new Date().toISOString(),
        output: resultPayload,
        n8n_execution_id,
        error: error_message || null,
      });
    if (insertErr) {
      callbackLog.error(
        "failed to insert run record",
        { err: insertErr.message, n8n_execution_id },
      );
      // Still return 200 so n8n does not retry
    }
  }

  // Update last-run bookkeeping on the workflow
  await supabaseAdmin
    .from("dante_workflows")
    .update({
      last_run_at: finished_at || new Date().toISOString(),
      last_run_status: status === "success" ? "success" : "error",
    })
    .eq("id", driftWorkflow.id);

  // If error, notify workspace owner (same pattern as existing run-executor)
  if (status === "error" && error_message) {
    try {
      const { notifyRunFailure } = await import("@/lib/dante/workflow-notifications");
      await notifyRunFailure({
        workflowId: driftWorkflow.id,
        workflowName: driftWorkflow.name,
        workspaceId: driftWorkflow.workspace_id,
        runId: n8n_execution_id,
        error: error_message,
      });
    } catch (notifyErr) {
      callbackLog.error(
        "failed to send failure notification",
        { err: String(notifyErr) },
      );
    }
  }

  return NextResponse.json({ ok: true, matched: true, drift_workflow_id: driftWorkflow.id });
}
