// scripts/test-full-pipeline.ts
//
// The exact flow the user described:
// "run due diligence on 1600 Euclid Ave Cleveland"
// -> DD data collection -> AI analysis -> PDF report -> email
//
// Usage: npx tsx --env-file=.env.local scripts/test-full-pipeline.ts

import { runWorkflow } from "../lib/dante/workflow-runner";
import type { WorkflowDefinition } from "../lib/dante/workflow-types";

const WORKSPACE = "5bc2cc7d-6e37-448b-836a-5df378ba6334";

// This is the exact "Property Due Diligence Report" template workflow,
// the one a broker would trigger by saying "run DD on 1600 Euclid Ave."
//
// 4 nodes: trigger -> due_diligence -> openai (analyze) -> generate_document
// Then we check if email would work (simulate mode for the send).

const pipeline: WorkflowDefinition = {
  id: "smoke-test-dd-pipeline",
  workspace_id: WORKSPACE,
  graph: {
    nodes: [
      {
        id: "trigger",
        type: "trigger_manual" as any,
        position: { x: 0, y: 0 },
        data: {
          step: {
            id: "trigger",
            type: "trigger_manual" as const,
            name: "Start",
            config: {},
          },
        },
      },
      {
        id: "dd",
        type: "due_diligence" as any,
        position: { x: 0, y: 100 },
        data: {
          step: {
            id: "dd",
            type: "due_diligence" as const,
            name: "Due Diligence",
            config: {
              address: "1600 Euclid Ave, Cleveland, OH 44115",
              drive_time_destinations:
                "Cleveland Hopkins Airport, Progressive Field, I-90 / I-71 interchange",
            },
          },
        },
      },
      {
        id: "analysis",
        type: "openai" as any,
        position: { x: 0, y: 200 },
        data: {
          step: {
            id: "analysis",
            type: "openai" as const,
            name: "AI Analysis",
            config: {
              model: "claude-sonnet-4-6",
              system:
                "You are a CRE due diligence analyst. Analyze the data and write a concise professional summary suitable for a branded report. Cover: location, demographics, employment trends, environmental risks, and nearby amenities. Be specific with numbers.",
              prompt: `Analyze this due diligence data for the property at {{steps.dd.location.formatted_address}}:

Location: {{steps.dd.location}}
Census Demographics: {{steps.dd.census}}
Employment Data: {{steps.dd.employment}}
Flood Zone: {{steps.dd.flood_zone}}
EPA Environmental: {{steps.dd.epa}}
Nearby Places: {{steps.dd.nearby_places}}
Drive Times: {{steps.dd.drive_times}}

Write a 3-section report: Executive Summary, Risk Assessment, Market Context.`,
              max_tokens: 1200,
            },
          },
        },
      },
      {
        id: "report",
        type: "generate_document" as any,
        position: { x: 0, y: 300 },
        data: {
          step: {
            id: "report",
            type: "generate_document" as const,
            name: "PDF Report",
            config: {
              title: "Due Diligence Report",
              subtitle: "{{steps.dd.location.formatted_address}}",
              sections: [
                {
                  heading: "Executive Summary",
                  body: "{{steps.analysis.text}}",
                },
                {
                  heading: "Employment Data",
                  body: "{{steps.dd.employment}}",
                },
                {
                  heading: "Environmental Assessment",
                  body: "{{steps.dd.epa}}",
                },
                {
                  heading: "Nearby Amenities",
                  body: "{{steps.dd.nearby_places}}",
                },
                {
                  heading: "Drive Times",
                  body: "{{steps.dd.drive_times}}",
                },
              ],
            },
          },
        },
      },
      {
        id: "email",
        type: "send_email" as any,
        position: { x: 0, y: 400 },
        data: {
          step: {
            id: "email",
            type: "send_email" as const,
            name: "Send Report",
            config: {
              to: "broker@example.com",
              subject:
                "Due Diligence Report: {{steps.dd.location.formatted_address}}",
              text: `Your due diligence report is ready.

{{steps.analysis.text}}

PDF Report: {{steps.report.url}}

Generated by Drift AI`,
            },
          },
        },
      },
    ],
    edges: [
      { id: "e1", source: "trigger", target: "dd" },
      { id: "e2", source: "dd", target: "analysis" },
      { id: "e3", source: "analysis", target: "report" },
      { id: "e4", source: "report", target: "email" },
    ],
  },
};

async function main() {
  console.log("=== Full Pipeline Smoke Test ===");
  console.log('Input: "run due diligence on 1600 Euclid Ave, Cleveland, OH 44115"');
  console.log(`Time: ${new Date().toISOString()}\n`);

  // Run with simulate=true so the email doesn't actually send,
  // but everything else (DD, AI, PDF) runs for real.
  const t0 = Date.now();
  const result = await runWorkflow(pipeline, {}, { simulate: true });
  const elapsed = ((Date.now() - t0) / 1000).toFixed(1);

  console.log(`\nPipeline completed in ${elapsed}s`);
  console.log(`Status: ${result.status}`);
  if (result.error) console.log(`Error: ${result.error}`);

  console.log(`\nStep-by-step log:`);
  for (const entry of result.log) {
    const icon = entry.status === "success" ? "OK" : "FAIL";
    const dur =
      entry.started_at && entry.finished_at
        ? `${((new Date(entry.finished_at).getTime() - new Date(entry.started_at).getTime()) / 1000).toFixed(1)}s`
        : "?";
    console.log(`  [${icon}] ${entry.step_name} (${entry.step_type}) -- ${dur}`);
    if (entry.error) console.log(`       Error: ${entry.error}`);
  }

  const out = result.output as Record<string, Record<string, unknown>>;

  // ── DD results ──
  const dd = out?.dd;
  if (dd) {
    const loc = dd.location as Record<string, unknown>;
    console.log(`\n-- Due Diligence --`);
    console.log(`  Address: ${loc?.formatted_address || "no geocode"}`);
    console.log(`  Coords: ${loc?.latitude}, ${loc?.longitude}`);
    console.log(`  County: ${loc?.county} (FIPS: ${loc?.state_fips}-${loc?.county_fips})`);

    const emp = dd.employment as unknown[];
    console.log(`  Employment records: ${emp?.length || 0}`);

    const census = dd.census;
    console.log(`  Census data: ${census ? "YES" : "no"}`);

    const flood = dd.flood_zone;
    console.log(`  Flood zone: ${flood ? "YES" : "unavailable"}`);

    const epa = dd.epa as Record<string, unknown>;
    const toxics = epa?.toxics_facilities as unknown[];
    const superfund = epa?.superfund_sites as unknown[];
    console.log(
      `  EPA: ${toxics?.length || 0} TRI facilities, ${superfund?.length || 0} Superfund sites`,
    );

    const nearby = dd.nearby_places as unknown[];
    console.log(`  Nearby places: ${nearby?.length || "none"}`);

    const drives = dd.drive_times as Array<Record<string, unknown>>;
    if (drives?.length) {
      console.log(`  Drive times:`);
      for (const d of drives) {
        console.log(`    ${d.destination}: ${d.duration_text} (${d.distance_text})`);
      }
    } else {
      console.log(`  Drive times: unavailable`);
    }

    const errors = dd.errors as string[];
    if (errors?.length) {
      console.log(`  Warnings: ${errors.join(", ")}`);
    }
  }

  // ── AI Analysis ──
  const analysis = out?.analysis;
  if (analysis) {
    const text = String(analysis.text || "");
    console.log(`\n-- AI Analysis --`);
    console.log(`  Length: ${text.length} chars`);
    console.log(`  Preview: ${text.slice(0, 200)}...`);
  }

  // ── PDF Report ──
  const report = out?.report;
  if (report) {
    console.log(`\n-- PDF Report --`);
    console.log(`  URL: ${report.url || "no URL (storage may not be configured)"}`);
    console.log(`  Size: ${report.size_bytes ? `${Math.round(Number(report.size_bytes) / 1024)}KB` : "?"}`);
    console.log(`  Filename: ${report.filename}`);
  }

  // ── Email (simulated) ──
  const email = out?.email;
  if (email) {
    console.log(`\n-- Email (simulated) --`);
    const would = (email as Record<string, unknown>).would_have as Record<
      string,
      unknown
    >;
    if (would) {
      console.log(`  To: ${would.to}`);
      console.log(`  Subject: ${would.subject}`);
      console.log(
        `  Preview: ${String(would.text_preview || "").slice(0, 150)}...`,
      );
    }
  }

  // ── Verdict ──
  console.log(`\n${"=".repeat(55)}`);
  const allOk = result.log.every((l) => l.status === "success");
  if (allOk && result.status === "success") {
    console.log("  VERDICT: Full pipeline works end to end.");
    console.log("  The broker types the address, gets a branded PDF in their inbox.");
  } else {
    console.log("  VERDICT: Pipeline has issues. See errors above.");
    process.exit(1);
  }
  console.log(`${"=".repeat(55)}`);
}

main().catch((e) => {
  console.error("FATAL:", e);
  process.exit(1);
});
