-- 20260503_regulatory_briefs.sql
--
-- Phase C3 follow-up — automated regulatory briefings.
--
-- The previous step (regulatory_corpus_*) made the data available
-- and surfaceable on demand: user opens the dashboard, sees a list
-- of new SEC/IRS/DOL/HUD items, clicks "Ask Dante what these mean
-- for my book." That's user-triggered analysis.
--
-- This step shifts to agent-triggered analysis: a cron runs after
-- each ingest, picks up workspaces where new items landed since
-- the last brief, and generates a structured briefing per
-- workspace — relevance, affected clients, recommended action —
-- without anyone asking. The user opens the dashboard and the
-- analysis is already there.
--
-- One row per (workspace_id, generated_at). The findings JSONB
-- carries the per-item analysis; UI reads from that. read_at lets
-- us surface "3 unread briefings" in the AppTopBar Ask button so
-- the user knows there's something to look at without having to
-- open the dashboard.

CREATE TABLE IF NOT EXISTS regulatory_briefs (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id    uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  generated_at    timestamptz NOT NULL DEFAULT now(),

  -- Window the brief covers. covering_since is the workspace's
  -- previous brief.generated_at (or far past if first brief);
  -- covering_until is generated_at. The cron uses this so a brief
  -- includes only items the user hasn't seen analyzed before.
  covering_since  timestamptz,
  covering_until  timestamptz NOT NULL DEFAULT now(),

  -- How many regulatory items were in scope vs. how many the
  -- agent flagged as actually relevant. Cheap counters for the UI
  -- summary line ("Dante reviewed 12 items; 3 affect your book").
  items_considered int  NOT NULL,
  items_relevant   int  NOT NULL,

  -- The per-item analysis the agent produced. Shape (TS-side):
  --   findings: Array<{
  --     item_id: uuid,
  --     authority: string,
  --     title: string,
  --     source_url: string,
  --     relevance: 'high' | 'medium' | 'low' | 'none',
  --     summary: string,                 // one-line implication
  --     affected_clients: Array<{contact_id?: string, name: string, why: string}>,
  --     recommended_action: string | null
  --   }>
  -- Stored verbatim so the UI doesn't have to call the LLM to
  -- re-render the analysis on every page load.
  findings        jsonb NOT NULL DEFAULT '[]'::jsonb,

  -- Audit trail: whose run produced this and which model.
  trigger_kind    text NOT NULL DEFAULT 'auto'
                       CHECK (trigger_kind IN ('auto', 'manual')),
  model           text,
  agent_version   text,

  -- Read-tracking. Per-user would require a separate join table;
  -- workspace-level is fine v1 because the briefs aren't private
  -- across the workspace — they're firm-wide context.
  read_at         timestamptz,
  read_by         uuid REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS regulatory_briefs_workspace_idx
  ON regulatory_briefs (workspace_id, generated_at DESC);
CREATE INDEX IF NOT EXISTS regulatory_briefs_unread_idx
  ON regulatory_briefs (workspace_id, generated_at DESC)
  WHERE read_at IS NULL;

ALTER TABLE regulatory_briefs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS regulatory_briefs_select ON regulatory_briefs;
CREATE POLICY regulatory_briefs_select ON regulatory_briefs
  FOR SELECT TO authenticated
  USING (
    workspace_id IN (
      SELECT workspace_id FROM profiles WHERE id = auth.uid()
    )
  );

-- Mark-read writes are app-mediated via /api/dante/regulatory-briefs
-- /[id]/read. We allow workspace members to UPDATE the read_at /
-- read_by columns; the API route guards against changing other
-- columns.
DROP POLICY IF EXISTS regulatory_briefs_mark_read ON regulatory_briefs;
CREATE POLICY regulatory_briefs_mark_read ON regulatory_briefs
  FOR UPDATE TO authenticated
  USING (
    workspace_id IN (
      SELECT workspace_id FROM profiles WHERE id = auth.uid()
    )
  )
  WITH CHECK (
    workspace_id IN (
      SELECT workspace_id FROM profiles WHERE id = auth.uid()
    )
  );

COMMENT ON TABLE regulatory_briefs IS
  'Agent-generated regulatory briefings. One row per workspace per cron run that finds new in-scope items. Stored as structured findings JSONB for cheap UI rendering. Generated by /api/dante/cron/regulatory-briefs after each ingest cron.';
